# Generated by Django 6.0.1 on 2026-01-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiemPhanAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('vi_do', models.FloatField(verbose_name='Vĩ độ (Lat)')),
                ('kinh_do', models.FloatField(verbose_name='Kinh độ (Lon)')),
                ('noi_dung', models.TextField(verbose_name='Nội dung phản ánh')),
                ('trang_thai', models.CharField(choices=[('Moi', 'Mới tiếp nhận'), ('DangXuLy', 'Đang xử lý'), ('DaXong', 'Đã xử lý xong')], default='Moi', max_length=20)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
