# Generated by Django 6.0.1 on 2026-02-03 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phan_anh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diemphananh',
            name='ngay_tao',
        ),
        migrations.RemoveField(
            model_name='diemphananh',
            name='noi_dung',
        ),
        migrations.AddField(
            model_name='diemphananh',
            name='ngay_bao_cao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian'),
        ),
        migrations.AddField(
            model_name='diemphananh',
            name='quan_huyen',
            field=models.CharField(choices=[('NinhKieu', 'Quận Ninh Kiều'), ('CaiRang', 'Quận Cái Răng'), ('BinhThuy', 'Quận Bình Thủy'), ('OMon', 'Quận Ô Môn'), ('ThotNot', 'Quận Thốt Nốt'), ('PhongDien', 'Huyện Phong Điền'), ('CoDo', 'Huyện Cờ Đỏ'), ('VinhThanh', 'Huyện Vĩnh Thạnh'), ('ThoiLai', 'Huyện Thới Lai')], default='NinhKieu', max_length=50, verbose_name='Quận/Huyện'),
        ),
        migrations.AlterField(
            model_name='diemphananh',
            name='kinh_do',
            field=models.FloatField(verbose_name='Kinh độ (Lng)'),
        ),
        migrations.AlterField(
            model_name='diemphananh',
            name='trang_thai',
            field=models.CharField(default='Moi', max_length=50, verbose_name='Trạng thái'),
        ),
    ]
