# Generated by Django 6.0.1 on 2026-02-05 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phan_anh', '0002_remove_diemphananh_ngay_tao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemphananh',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú xử lý'),
        ),
        migrations.AddField(
            model_name='diemphananh',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='anh_hien_truong/', verbose_name='Ảnh hiện trường'),
        ),
        migrations.AddField(
            model_name='diemphananh',
            name='ngay_cap_nhat',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật cuối'),
        ),
        migrations.AlterField(
            model_name='diemphananh',
            name='kinh_do',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='diemphananh',
            name='ngay_bao_cao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diemphananh',
            name='quan_huyen',
            field=models.CharField(choices=[('NinhKieu', 'Quận Ninh Kiều'), ('CaiRang', 'Quận Cái Răng'), ('BinhThuy', 'Quận Bình Thủy'), ('OMon', 'Quận Ô Môn'), ('ThotNot', 'Quận Thốt Nốt'), ('PhongDien', 'Huyện Phong Điền'), ('CoDo', 'Huyện Cờ Đỏ'), ('VinhThanh', 'Huyện Vĩnh Thạnh'), ('ThoiLai', 'Huyện Thới Lai')], default='NinhKieu', max_length=50),
        ),
        migrations.AlterField(
            model_name='diemphananh',
            name='trang_thai',
            field=models.CharField(default='Moi', max_length=50),
        ),
        migrations.AlterField(
            model_name='diemphananh',
            name='vi_do',
            field=models.FloatField(),
        ),
    ]
