# Generated by Django 6.0.1 on 2026-04-07 09:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiemPhanAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('quan_huyen', models.CharField(default='Chưa xác định', max_length=100, verbose_name='Khu vực')),
                ('vi_do', models.FloatField()),
                ('kinh_do', models.FloatField()),
                ('trang_thai', models.CharField(default='ChoDuyet', max_length=50)),
                ('ngay_bao_cao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú xử lý')),
                ('hinh_anh_xong', models.ImageField(blank=True, null=True, upload_to='anh_da_xu_ly/', verbose_name='Ảnh đã xử lý xong')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật cuối')),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sao', models.IntegerField(default=5)),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diem_phan_anh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_binh_luan', to='phan_anh.diemphananh')),
            ],
        ),
        migrations.CreateModel(
            name='HinhAnhPhanAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='anh_hien_truong/')),
                ('diem_phan_anh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_hinh_anh', to='phan_anh.diemphananh')),
            ],
        ),
    ]
