# Generated by Django 6.0.1 on 2026-04-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phan_anh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binhluan',
            name='sao',
        ),
        migrations.AddField(
            model_name='binhluan',
            name='hinh_anh_minh_chung',
            field=models.ImageField(blank=True, null=True, upload_to='anh_binh_luan/'),
        ),
        migrations.AddField(
            model_name='binhluan',
            name='loai_phan_hoi',
            field=models.CharField(choices=[('GopY', '💬 Góp ý / Bình luận'), ('XacNhan', '✅ Xác nhận đã khắc phục'), ('PhanDo', '❌ Báo cáo sai / Vẫn chưa sửa')], default='GopY', max_length=20),
        ),
        migrations.AddField(
            model_name='diemphananh',
            name='mo_ta_chi_tiet',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AlterField(
            model_name='diemphananh',
            name='tieu_de',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề ngắn'),
        ),
    ]
