# Generated by Django 6.0.1 on 2026-04-14 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phan_anh', '0002_remove_binhluan_sao_binhluan_hinh_anh_minh_chung_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binhluan',
            name='loai_phan_hoi',
        ),
        migrations.AddField(
            model_name='diemphananh',
            name='nguoi_thich',
            field=models.ManyToManyField(blank=True, related_name='cac_diem_da_thich', to=settings.AUTH_USER_MODEL),
        ),
    ]
