# Generated by Django 6.0.1 on 2026-04-14 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phan_anh', '0003_remove_binhluan_loai_phan_hoi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diemphananh',
            name='nguoi_thich',
        ),
        migrations.AddField(
            model_name='diemphananh',
            name='nguoi_theo_doi',
            field=models.ManyToManyField(blank=True, related_name='cac_diem_dang_theo_doi', to=settings.AUTH_USER_MODEL),
        ),
    ]
