# Generated by Django 6.0.1 on 2026-04-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phan_anh', '0004_remove_diemphananh_nguoi_thich_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diemphananh',
            name='an_danh',
            field=models.BooleanField(default=False, verbose_name='Ẩn danh'),
        ),
        migrations.AlterField(
            model_name='diemphananh',
            name='tieu_de',
            field=models.CharField(max_length=200, verbose_name='Tiêu đề'),
        ),
    ]
