# Generated by Django 6.0.1 on 2026-04-15 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phan_anh', '0005_diemphananh_an_danh_alter_diemphananh_tieu_de'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diemphananh',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ cụ thể'),
        ),
        migrations.AddField(
            model_name='diemphananh',
            name='nguoi_xac_nhan',
            field=models.ManyToManyField(blank=True, related_name='cac_diem_da_xac_nhan', to=settings.AUTH_USER_MODEL),
        ),
    ]
