# Generated by Django 6.0.1 on 2026-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phan_anh', '0006_diemphananh_dia_chi_diemphananh_nguoi_xac_nhan'),
    ]

    operations = [
        migrations.AddField(
            model_name='binhluan',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='binhluan',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
